### ISSUE TITLE
No such module 'SecondSceneFramework'

### ISSUE THREAD

**Issue by rollr76518** [markjarecki/FlowControllerExample#4]
Hello, Sir

I follow the steps but Xcode show me the message.

Steps:
```
1. git clone https://github.com/markjarecki/FlowControllerExample.git
2. cd FlowControllerExample
3. Open FlowControllerExample.xcworkspace in Xcode
4. Built it and run
```

Messager:
`No such module 'SecondSceneFramework'`

It's a interesting project, I'd like to build it and learned by use.

**Comment by markjarecki** [comment]
Are you sure you are opening the workspace and NOT the project? I only say this as I have followed these instructions on two different systems and don't have any issues. What version of Xcode are you using?

**Comment by markjarecki** [comment]
Also, is your Xcode **active scheme** in the scheme selector showing **FlowControllerExample**?

**Comment by rollr76518** [comment]
Oh, thanks man.

Because I clone the project from the github, and the folder name is `FlowControllerExample-Master` , so below steps are all wrong.

Now I can run it now, thank you very much~

**Comment by markjarecki** [comment]
Yeah, if you just use `clone` from the command line, you shouldn't get that issue. Next time, I'll try to be more specific. Cheers.
